### ISSUE TITLE
How to handle page snippet loaded with atom controls?

### ISSUE THREAD

**Issue by accessizer** [neurospeech/web-atoms.js#136]
It's not clear from the documentation how one should load a section of the page by doing $("#someDiv").load(). In my testing, it seems that atom control doesn't get completely initialized but I might be doing it wrong. What is the typical approach for loading a piece of HTML fragment that contains atoms control?

**Comment by neurospeech** [comment]
Web Atoms Framework works little differently, you never use $ sign anywhere. You have to follow concepts of Model and View as defined in 

http://web-atoms.neurospeech.com/docs/index.html#view=concepts%2Findex.html

at

http://web-atoms.neurospeech.com/

It has to start with an application defined at top level given in this example.

http://web-atoms.neurospeech.com/docs/index.html#view=control.html%23overview%3Datom-application

**Comment by accessizer** [comment]
Let me try and rephrase the question a bit. 

If I've already loaded the atom application and controls. The user clicks a button that should then pull a new section that is currently not loaded. How do I then load new atom controls and the template for a subsection of the application? The examples given so far seems to assume that I define all the controls I want on the page ahead of the time but I want to load only few controls at a time and then load controls when they actually ask for it.

**Comment by neurospeech** [comment]
All UI elements needed to be shown must exist right from beginning, however, if you look at Scope templates, UI is defined but only instantiated when needed. Take example of List and Templates. Atom Frame View and Templates.
